### ISSUE TITLE
Sugiero cambiar fondo a blanco en todas las posibles vistas o... (leer abajo)

### ISSUE THREAD

**Issue by emiliomorles** [yanicroft/Web-personal-Yanira#8]
Porque desde Mobile landscape (480x320) hasta Tablet portrait (768x1024) se ve fondo amarillo y hace que tu icono se vea mal. O la otra posibilidad es hacer un PNG redondo de tu icono con los bordes cuadrados transparentes y así no se vera mal con el fondo ;)

**Comment by yanicroft** [comment]
Muchas gracias por tu sugerencia. Ya lo acomodé.
